config/routes.rb
Rails.application.routes.draw do
  # resources :homes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'homes#index'
    get 'privacy', to: 'privacy#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/privacy_controller.rb
class PrivacyController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<div class="container-fluid pages" id="home">
  <div class="col-md-12 no-gutters" id="header"> 
<div style="position: fixed; z-index: -99; width: 100%; height: 100%"  id="video">
      <iframe frameborder="0" height="100%" width="100%" 
        src="https://www.youtube.com/embed/utGVCbTFWBo?autoplay=1&loop=1&controls=0&showinfo=0&autohide=1&mute=1" allow="autoplay allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen" >
      </iframe>

 </div>
    <div class="row no-gutters" >
      
      <%= image_tag image_url('https://bkartistsocial.s3.amazonaws.com/logobw3.png'), id: "logo"  %>
      <%= image_tag image_url('https://bkartistsocial.s3.amazonaws.com/title4.png'), id: "title" %>
      <p class="links" id="link1"><%= link_to "Events", "/event"%></p>
      <p class="links" id="link2"><%= link_to "New Artists", "/newartist"%></p>
      <p class="links" id="link3"><%= link_to "Contact", "/contact"%></p>
    </div>
  </div>
</div>
<!-- <div style="position: fixed; z-index: -99; width: 100%; height: 100%">
      <iframe frameborder="0" height="100%" width="100%" 
        src="https://www.youtube.com/embed/utGVCbTFWBo?autoplay=1&controls=0&showinfo=0&autohide=1">
      </iframe>

 </div> -->

<div class="container-fluid pages" id="home2">
  <div class="row">
    
  </div>
</div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/_footer.html.erb
<div class="container-fluid no-gutters pages" id="footer">

	<div class="row">
		<div class="logo">
			<h4>BK Artist Social</h4>
		</div>
	</div>

	<!-- <div class="socialmedia row">
		<#%= link_to href: 'http://www.example.com/' do %>
    	<#%= image_tag image_url('https://bkartistsocial.s3.amazonaws.com/bkaslogo4.png') %>
		<#% end %>
		<#%= link_to href: 'https://www.instagram.com/bkartistsocial/' do %>
    	<#%= image_tag image_url('https://bkartistsocial.s3.amazonaws.com/whinsta.png') %>
		<#% end %>
		<#%= link_to href: 'http://www.example.com/' do %>
    	<#%= image_tag image_url('https://s3.amazonaws.com/nordicsites/blyt2.png') %>
		<#% end %>

	</div> -->

	<div class="row">
		<p><%= link_to "Events", "/event"%></p>
		<p><%= link_to "New Artists", "/newartist"%></p>
		<p><%= link_to "Contact", "/contact"%></p>
		<p><%= link_to "Privacy Policy", "/privacy"%></p>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bkartistsocial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap-grid.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

     <link href="https://fonts.googleapis.com/css2?family=Abel&family=Cinzel&display=swap" rel="stylesheet">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render '/layouts/header' %>

    <%= yield %>

    <%= render '/layouts/footer' %>

  </body>
</html>

app/views/privacy/index.html.erb
<div class="row" id="privacypolicy">
	<div class="col-md-12">
		<h2>Privacy Policy</h2>
	</div>
	<div class="col-md-10 background">
		<p>This privacy notice discloses the privacy practices for (website address). This privacy notice applies solely to information collected by this website. It will notify you of the following:</p>
		<ol>
			<li>What personally identifiable information is collected from you through the website, how it is used and with whom it may be shared.</li>
			<li>What choices are available to you regarding the use of your data.</li>
			<li>The security procedures in place to protect the misuse of your information.</li>
			<li>How you can correct any inaccuracies in the information.</li>
		</ol>
		<b><p>Information Collection, Use, and Sharing</p></b>
		We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.</p>

		<p>We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g. to ship an order.</p>

		<p>Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.</p>

		<b><p>Your Access to and Control Over Information</p></b>
		<p>You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address or phone number given on our website:</p>
		<ul>
			<li>See what data we have about you, if any.</li>
			<li>Change/correct any data we have about you.</li>
			<li>Have us delete any data we have about you.</li>
			<li>Express any concern you have about our use of your data.</li>
		</ul>
		<b><p>Security</p></b>
		<p>We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.</p>

		<p>Wherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a lock icon in the address bar and looking for "https" at the beginning of the address of the Web page.</p>

		<p>While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.</p>

		<b><p>If you feel that we are not abiding by this privacy policy, you should contact us immediately at bkartistsocial@gmail.com.</p></b>
	</div>
	

</div>